# Generated by Django 5.0.1 on 2024-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_Address', models.TextField()),
                ('Date', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
            ],
        ),
    ]
