# Generated by Django 5.0.1 on 2024-02-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_appointment',
            name='Title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
