# Generated by Django 5.0.1 on 2024-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_appointment',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='add_appointment',
            name='Time',
            field=models.TimeField(),
        ),
    ]
